# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/52695868/serializers-django-rest-framework-attributeerror-got-attributeerror-when-att
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
top_keywords=_c_(427500, _a_(427499, _c_(427498, _a_(427497, _c_(427496, _a_(427492, _a_(427491, _n_(427490, "UserKeyword", lambda: UserKeyword), "objects"), "filter"), user_id=_a_(427495, _a_(427494, _n_(427493, "request", lambda: request), "user"), "id")), "select_related")), "order_by"), '-count')
_l_(427501)
user_serializer=_a_(427505, _c_(427504, _n_(427502, "UserKeywordSerializer", lambda: UserKeywordSerializer), _n_(427503, "top_keywords", lambda: top_keywords)), "data")
_l_(427506)
_c_(427509, _n_(427507, "print", lambda: print), _n_(427508, "user_serializer", lambda: user_serializer))
_l_(427510)