# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/77258112/file-not-found-error-in-python-while-the-file-already-exists
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
data = _c_(372645, _a_(372644, _n_(372643, "pd", lambda: pd), "read_csv"), 'C:\\city_day.csv')
_l_(372646)