# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/50913997/tensorflow-typeerror-tensorshape-object-is-not-callable
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
var_b = _c_(537185, _a_(537176, _n_(537175, "tf", lambda: tf), "get_variable"), 'name_a',shape=[_c_(537179, _a_(537178, _n_(537177, "input_x", lambda: input_x), "get_shape"))[0],2],dtype=_a_(537181, _n_(537180, "tf", lambda: tf), "float32"),initializer=_c_(537184, _a_(537183, _n_(537182, "tf", lambda: tf), "random_uniform_initializer")))
_l_(537186)